# Ansible Inventory
# For udrulning af VM'er og containere via Proxmox REST API kører playbooks lokalt på din egen computer.
# Ansible snakker direkte med Proxmox API'et ved hjælp af Python-biblioteket 'proxmoxer'.

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
